### ISSUE TITLE
Passman does not show the last alphabetical entry

### ISSUE THREAD

**Issue by blacs30** [Y0nnyy/passman-ios#7]
It seems that the last alphabetical entry is not displayed in the app.

I created new entries, one in the middle of the existing credentials, it was displayed correctly. When I create one at the end of the list it will not be shown in the app.

<img width="736" alt="screen shot 2018-02-22 at 01 47 42" src="https://user-images.githubusercontent.com/11589882/36514214-bb6e22c6-1773-11e8-9ee4-fbda4d3dd010.png">
<img width="859" alt="screen shot 2018-02-22 at 01 48 06" src="https://user-images.githubusercontent.com/11589882/36514215-bb84088e-1773-11e8-9700-625cd3d23aa5.png">

**Comment by Y0nnyy** [comment]
@blacs30 thank you for reporting the issue. I made a bug fix. Please try again after pulling and building it again ;)

**Comment by claaslisowski** [comment]
@Y0nnyy, thanks for the fix. Working now here for me too.
