### ISSUE TITLE
Passman main devs contact

### ISSUE THREAD

**Issue by animalillo** [Y0nnyy/passman-ios#9]
If you have any questions or need any help or clarification on how to approach anything on this project, feel free to contact any of us at telegram!
https://t.me/brantje (Github @Brantje, obviously)
https://t.me/wolfi (Github @Animalillo)

**Comment by animalillo** [comment]
You could also join the passman general talk group (https://t.me/passman_general)

**Comment by Y0nnyy** [comment]
@animalillo alright, thank you. I joined the passman general group.
